version: "3.7"
services:
  
  drupal:
    image: drupal:8.8.5-apache
    ports:
      - "8080:80"
  
  psgql:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: s3cret
